name: Build APP

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - assembleNsfwDisabledNoKeyDozeEnabledBillingDisabled
          - assembleNsfwEnabledNoKeyDozeEnabledBillingDisabled
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract directory
        id: extract_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return '${{ matrix.task }}'.replace('assembleN', 'n');
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew ${{ matrix.task }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_name.outputs.result }}
          path: app/build/outputs/apk/${{ steps.extract_name.outputs.result }}/release/*.apk
          if-no-files-found: error
          retention-days: 1
