name: Build APP

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - assembleNsfwDisabledNoKeyDozeEnabledBillingDisabled
          - assembleNsfwEnabledNoKeyDozeEnabledBillingDisabled
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract directory
        id: extract_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return '${{ matrix.task }}'.replace('assembleN', 'n');
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up API keys
        run: |
          echo "prod_api_key=0000000000" >> local.properties
          echo "dev_api_key=0000000000" >> local.properties
      - name: Build with Gradle
        run: ./gradlew ${{ matrix.task }}
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/${{ steps.extract_name.outputs.result }}/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_name.outputs.result }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
          retention-days: 1
